英語版・やさしいにほんご版のi18n対応
gdg-fukushima/covid19 pull request #22
Opened 2020-04-01 12:06 UTC by koheitakahashi

## 👏 解決する issue / Resolved Issues
close #12 

## 📝 関連する issue / Related Issues

## ⛏ 変更内容 / Details of Changes

-  en.json, ja-basic.json ファイルを作成し、適宜翻訳を行う。

## 📸 スクリーンショット / Screenshots

2020-04-04 10:08 UTC, koheitakahashi commented
@donuzium
レビュー、よろしくお願いいたします🙇‍♂️

2020-04-04 15:02 UTC, donuzium requested changes
ありがとうございます！福島版にしかない文章などの翻訳もありがとうございました。
言語切替の動きなどについては問題なと思います。

1点「新型コロナウィルスが心配なときに」のページがエラーで表示されない状態になっているようです。
この点が解決すればマージできると思いますのでご確認ください！

2020-04-05 02:41 UTC, koheitakahashi commented
@donuzium 
レビューいただき、ありがとうございます🙇‍♂️

1点確認させていただきたいのですが、

> 「新型コロナウィルスが心配なときに」のページがエラーで表示されない状態になっているようです。

こちら、私のローカルでは、エラーにならずに表示されております🤔
consoleの方にも、それらしきエラーは見当たりません。

対応させていただきたいので、どのようなエラーメッセージなのか教えていただいてもよろしいでしょうか?🤔

以下、私の環境での「新型コロナウィルスが心配なときに」のページのスクリーンショット

[![Image from Gyazo](https://i.gyazo.com/636d421ef3a76bced9dd7f319ceba3ae.png)](https://gyazo.com/636d421ef3a76bced9dd7f319ceba3ae)

[![Image from Gyazo](https://i.gyazo.com/bd1b5b9e90e2405f92f04ac2c2b393ae.png)](https://gyazo.com/bd1b5b9e90e2405f92f04ac2c2b393ae)

[![Image from Gyazo](https://i.gyazo.com/bc8ceb7ea04e55dff0236e450b57bfae.png)](https://gyazo.com/bc8ceb7ea04e55dff0236e450b57bfae)

2020-04-05 08:12 UTC, donuzium commented
@koheitakahashi 
そちらの環境を見ると、普通に動いてそうですね。

こっちでブランチを持ってきてやってみると、以下のようなエラーが、リンクを押したタイミングで出ている状態でした。
```
componentNormalizer.js?2877:24 Uncaught (in promise) TypeError: Cannot set property 'render' of undefined
    at normalizeComponent (componentNormalizer.js?2877:24)
    at eval (FlowSpAdvisory.vue?046f:42)
    at Module../components/flow/FlowSpAdvisory.vue (flow.js:155)
    at __webpack_require__ (runtime.js:790)
    at fn (runtime.js:151)
    at eval (index.js?!./node_modules/vue-loader/lib/index.js?!./components/flow/FlowSp.vue?vue&type=script&lang=js&:8)
    at Module../node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./components/flow/FlowSp.vue?vue&type=script&lang=js& (flow.js:539)
    at __webpack_require__ (runtime.js:790)
    at fn (runtime.js:151)
    at eval (FlowSp.vue?aa75:1)
```

<img width="1415" alt="Screen Shot 2020-04-05 at 17 06 08" src="https://user-images.githubusercontent.com/1407941/78469865-db1e0e80-775f-11ea-882c-2aa7769a8929.png">

```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <Nuxt>
         <VApp>
           <Layouts/default.vue> at layouts/default.vue
             <Root>
```

ただおそらくそちらの環境では再現してなそうですよね。う〜む🤔

2020-04-05 11:44 UTC, koheitakahashi commented
@donuzium 
エラーログ、ありがとうございます🙇‍♂️
拝見しましたが、今パッとは分からないので、ちょっと原因調査してみます。
明日くらいに、結果をお伝えさせていただければと思います🙇‍♂️

2020-04-05 17:05 UTC, donuzium commented
@koheitakahashi ありがとうございます！

こちらもちょっと見てみると、こんなIssueがあってキャッシュの問題っぽかったので、node_modules自体消してやり直したところ正常に表示されました🎉
https://github.com/mzgoddard/hard-source-webpack-plugin/issues/416#issuecomment-411832075

ソース自体も問題ないと思いますのでマージしますね。

2020-04-05 17:05 UTC, donuzium approved these changes

2020-04-05 17:09 UTC, merged

2020-04-06 02:00 UTC, koheitakahashi commented
@donuzium 

>こんなIssueがあってキャッシュの問題っぽかったので、node_modules自体消してやり直したところ正常に表示されました🎉

なるほど、自分で調べてて分からなかったので、勉強になりました🙇‍♂️

> ソース自体も問題ないと思いますのでマージしますね。

ありがとうございます🙇‍♂️🙇‍♂️